#! /usr/local/bin/zsh

theme=$([ $1 ] && [ $1 = 'Light' ] && echo 'light' || echo 'dark')

sed -i '' -r "s/^(local theme = ).*/\1\'$theme\'/" ~/.config/wezterm/wezterm.lua

if [ $theme = 'light' ]; then
	BAT_THEME='Coldark-Cold'
else
	BAT_THEME='Coldark-Dark'
fi
export BAT_THEME

